ready for second review
MAChapurin/javascript-advanced pull request #2
Opened 2023-06-07 17:43 UTC by MAChapurin

2023-06-11 13:26 UTC, Grinv requested changes

2023-06-11 13:26 UTC, Grinv commented on 04-timer/main.js
> +let timerId = null;
Можно сразу объявить интервал тут, тогда он станет const
```javascript
const timerId = setInterval(updateDate, 1000);

2023-06-11 13:26 UTC, Grinv commented on 04-timer/main.js
> +  document.querySelector(
Нет смысла делать селект в каждом интервале, если элемент у тебя не меняется, это не очень хорошо влияет на производительность и нам приходится совершать лишние действия. Можешь вынести за функцию (туда, где объявляется timerId) и просто обращаться к этому элементу через переменную.
```javascript
const timerElement = document.querySelector('.title');
function updateDate() {
   ///....
   timerElement.textContent(...);
   ///....
}

2023-06-11 13:26 UTC, Grinv commented on 04-timer/main.js
> +function getIndexForWord(num) {
Молодец, что об этом подумал. Есть устоявшееся и правильное название для такой функции `pluralize`

2023-06-11 13:26 UTC, Grinv commented on 04-timer/main.js
> +  return 2;
Молодец. Давай попробуем заюзать уже нативный метод из Js `Intl.PluralRules`.
Пример, как сделать, можешь найти тут: https://2ality.com/2019/12/intl-pluralrules.html

2023-06-11 13:26 UTC, Grinv commented on 04-timer/main.js
> +  const newYear = new Date(2024, 0, 1, 0, 0, 0);
А если мы будет считать 1 января 2024 года, функция уже работать не будет :) Давай сделаем более полезной и будет вычислять дату до следующего НГ, отталкиваясь от текущей

2023-06-11 13:26 UTC, Grinv commented on 04-timer/main.js
> +  const hours = restTime > 0 ? Math.floor(restTime / 1000 / 60 / 60) % 24 : 0;
Лучше магические  числа выносить в константы и использовать их (и вынести за функцию). Тогда читать будет проще и другим разработчикам будет понятнее, откуда взялось это число.
```javascript
const MINUTE_IN_MILLISECONDS = 1000 * 60;
const HOUR_IN_MILLISECONDS = MINUTE_IN_MILLISECONDS * 60;

2023-06-11 13:26 UTC, Grinv commented on 04-timer/main.js
> +  }`;
Давай лучше сначала сделаем строку контента, потом уже вставим в элемент, так читается проще.
```javascript
const text = `До нового года осталось ...`;
timerElement.textContent(text);

2023-06-11 13:26 UTC, Grinv commented on 06-class/index.js
> +  #_mark;
Не надо сразу оба способа применять. Лучше определиться, как мы пишем или `#mark` или `_mark`

2023-06-11 13:26 UTC, Grinv commented on 06-class/index.js
> +    (this.#_mark = mark), (this.#_model = model), (this.#_milliage = milliage);
Сложно читать и смысла нет, давай лучше так:

```javascript
this.#mark = mark;
this.#model = model;
this.#milliage = milliage;

2023-06-11 13:26 UTC, Grinv commented on 06-class/index.js
> +    this.milliage = miles ? miles : 0;
Тут можно воспользоваться современным JS :)
```javascript
this.milliage = miles ?? 0;
```

Ну а вообще не понятно, зачем этот метод. Давай лучше в сеттере будем делать всю проверку, он нам для этого и нужен.

2023-06-11 13:26 UTC, Grinv commented on 05-oop/index.js
> +  return ork;
Эм, а зачем делать прототип орка, чтоб из него вернуть person. В чём тогда смысл прототипа Ork?

2023-06-11 13:26 UTC, Grinv commented on 05-oop/index.js
> +// console.log(ork instanceof Ork);
Фактически да. Но если заглянуть например в ork.constructor, то окажется, что это Person. а должен быть Ork

Фактически ты подменил конструктор орка на конструктор персоны и сделал объект

Можешь например прочитать вот эту статью и сделать на её примере: https://www.digitalocean.com/community/tutorials/understanding-prototypes-and-inheritance-in-javascript

2023-06-29 16:05 UTC, Grinv commented
А где исправления по комментариям?

2023-06-29 16:26 UTC, MAChapurin commented
Второй коммит надо смотреть

2023-06-29 18:25 UTC, Grinv requested changes

2023-06-29 18:25 UTC, Grinv commented on 04-timer/main.js
> +      throw new Error('Unknown: ' + grammaticalNumber);
👍

2023-06-29 18:25 UTC, Grinv commented on 04-timer/main.js
> +const newYear = new Date(2077, 0, 1);
Нет, не совсем правильно понял. Тебе не надо хардкодить дату следующего НГ, до которого работает таймер.
Когда ты хардкодить, оно будет работать ровно до следующего года. В 2024 тебе придётся переписать скрипт, чтоб он снова работал.
Так же обычно и в приложениях в футере в копирайтах год не хардодят, а просто динамически вычисляют.
Тебе надо взять new Date(), засетить дату нового года именно в этом вычисленном году и уже от него считать таймер

2023-06-29 18:25 UTC, Grinv commented on 04-timer/main.js
> +  updateDate(title1, newYear, timerId1, 'До нового 2077 года остается');
Почему 2077?))

2023-06-29 18:25 UTC, Grinv commented on 05-oop/index.js
> +console.log(elf);
Да, теперь правильно, молодец

2023-06-29 18:25 UTC, Grinv commented on 04-timer/main.js
> +  const seconds = Math.floor(restTime / SECUNDS_IN_MILLISECONDS) % 60;
TYPO SECOND_IN_MILLISECONDS

А вообще да, правильно понял

2023-06-29 18:25 UTC, Grinv commented on 04-timer/main.js
> +}, 1000);
Зачем столько таймеров?)
Тебе нужен один таймер, который вычисляет время до конца текущего года. Текущий год динамический. Сейчас 2023, через полгода будет 2024, скрипт должен это учитывать и динамически считать дату от этого года

2023-06-29 18:25 UTC, Grinv commented on 06-class/index.js
> +    (this.#mark = mark), (this.#model = model), (this.#milliage = milliage);
Не поправил. Читать неудобно.
```javascript
this.#mark = mark;
this.#model = model;
this.#milliage = milliage;

2023-06-29 18:25 UTC, Grinv commented on 06-class/index.js
> +    if (typeof miles === 'number' && miles >= 0) {
👍

2023-06-29 18:25 UTC, Grinv commented on 06-class/index.js
> +    this.milliage = miles ?? 0;
Зачем? Я опять же в комментариях писал, у тебя есть прекрасный `set milliage`, используй его
Две функции, которые делают одно и тоже.

2023-06-29 18:25 UTC, Grinv commented on 04-timer/main.js
> +  // console.log(restTime)
Лишние и забытые комменты нужно удалять перед отправкой на ревью. И вообще лучше в коде не держать)

2023-06-29 18:25 UTC, Grinv commented on 04-timer/main.js
> +const title1 = document.querySelector('.title1');
Лучше .timer1, а не .title1. Лучше подходит

Ну а вообще лучше в таких ситуациях использовать id и искать при помощи getElementById, он быстрее работает

2023-06-29 18:38 UTC, MAChapurin commented on 04-timer/main.js
> +const newYear = new Date(2077, 0, 1);
Я немного улучшил чтобы считать не до нг, а до конкретной даты

2023-06-29 18:39 UTC, MAChapurin commented on 04-timer/main.js
> +  updateDate(title1, newYear, timerId1, 'До нового 2077 года остается');
Проходил киберпанк недавно, пасхалка типа

2023-06-29 18:44 UTC, MAChapurin commented on 06-class/index.js
> +    this.milliage = miles ?? 0;
Это была функция скручивания пробега(, удалю

2023-06-29 18:44 UTC, MAChapurin commented on 04-timer/main.js
> +  // console.log(restTime)
ок

2023-06-29 18:49 UTC, MAChapurin commented on 04-timer/main.js
> +const title1 = document.querySelector('.title1');
сейчас подправлю

2023-06-29 19:20 UTC, MAChapurin commented on 06-class/index.js
> +    (this.#mark = mark), (this.#model = model), (this.#milliage = milliage);
Это редактор кода выдает при сохранении

2023-06-29 19:21 UTC, MAChapurin commented on 06-class/index.js
> +    (this.#mark = mark), (this.#model = model), (this.#milliage = milliage);
Дело было в запятых

2023-07-02 11:42 UTC, Grinv approved these changes

2023-07-02 11:42 UTC, Grinv commented on 04-timer/main.js
> +    new Date(2024, 0, 1),
Тебе надо это делать не руками, а вычислять динамически при выполнении скрипта, пытаемся всё автоматизировать максимально. Уже ж несколько раз писал.
https://github.com/MAChapurin/javascript-advanced/pull/2/files#r1232283997
Вот тут в комментарии я написал.
Берёшь new Date(), тебе приходит дата `(dd)-(mm)-(yyyy)`, тебе надо сделать `(01)-(01)-(yyyy+1)`

2023-07-02 11:42 UTC, Grinv commented on 04-timer/main.js
> +  // console.log(restTime)
Написал ок, а так и не удалил

2023-07-02 11:42 UTC, merged