Review3
MAChapurin/javascript-advanced pull request #3
Opened 2023-06-23 16:50 UTC by MAChapurin

2023-06-24 14:39 UTC, Grinv requested changes

2023-06-24 14:39 UTC, Grinv commented on 04-timer/main.js
> +}, 1000);
Отправь пожалуйста 4, 5, 6 задачи в предыдущем ПР, я там проверю. Не надо всё сбрасывать в одну кучу :)

2023-06-24 14:39 UTC, Grinv commented on 08-solid/index.js
> +console.log(itemsBill.calculateTotal(['good1', 'good2', 'good3']));
Да, всё правильно, молодец

2023-06-24 14:39 UTC, Grinv commented on 07-oop-in-class/index.js
> +  #race = 'Орк';
Зачем? Тебе надо расу прокинуть в прототип Person и оттуда брать.

2023-06-24 14:39 UTC, Grinv commented on 07-oop-in-class/index.js
> +    super(race, name, language), (this.race = this.#race), (this.weapon = weapon);
Пожалуйста, я уже 3 раз прошу, не пиши так. Выглядит ужасно нечитабельно и комментировать неудобно :)
```javascript
super(race, name, language);
this.weapon = weapon;

2023-06-24 14:39 UTC, Grinv commented on 07-oop-in-class/index.js
> +    super(race, name, language), (this.race = this.#race), (this.weapon = weapon);
```javascript
this.race = this.#race
```
Зачем хранить race в 2 местах? Нужно прокинуть просто в родителя Person через super и оттуда брать. Какой тогда вообще смысл в наследовании? :)

2023-06-24 14:39 UTC, Grinv commented on 07-oop-in-class/index.js
> +  }
Тоже самое, что и с орком

2023-06-24 14:39 UTC, Grinv commented on 09-pokemon/main.js
> +    console.log(newXhr.response.effect_entries[1].effect);
Вспоминаем про SOLID про букву S. Функция должна заниматься только одним - забирать данные и возвращать.
console.log - это лишний сайд-эффект и она одна не должна ничего про это знать.
Поэтому нужно вызвать функцию, забрать оттуда данные и отдельно законсолить.

2023-06-24 14:39 UTC, Grinv commented on 09-pokemon/main.js
> +
А ещё в качестве доп. задания, когда дойдёшь до промисов, можешь вернуть обратно сюда к заданию и попробовать сделать промисификацию этой функции.
Почитать можно например тут: https://learn.javascript.ru/promisify

2023-06-27 06:31 UTC, MAChapurin commented on 04-timer/main.js
> +}, 1000);
Так они там и отправлены, some changes коммит

2023-06-27 06:34 UTC, MAChapurin commented on 07-oop-in-class/index.js
> +    super(race, name, language), (this.race = this.#race), (this.weapon = weapon);
Ивини, я разом все домашки написал и не перепроверил перед отправкой

2023-06-27 06:44 UTC, MAChapurin commented on 07-oop-in-class/index.js
> +  #race = 'Орк';
Меня смутило что можно например при инициалицации написать, ну например Троль, и будет сласс Орк, у которого в свойстве расса не то что мы ожидаем

2023-06-27 06:49 UTC, MAChapurin commented on 07-oop-in-class/index.js
> +    super(race, name, language), (this.race = this.#race), (this.weapon = weapon);
Подправил

2023-06-27 07:12 UTC, MAChapurin commented on 09-pokemon/main.js
> +    console.log(newXhr.response.effect_entries[1].effect);
Ну тут имитация Callback Hell, ну что-то попытался изобразить

2023-06-29 20:08 UTC, closed without merging