ready for four review
MAChapurin/javascript-advanced pull request #5
Opened 2023-07-07 11:04 UTC by MAChapurin

2023-07-08 15:56 UTC, Grinv requested changes

2023-07-08 15:56 UTC, Grinv commented on 10-pokemon-promise/main.js
> +  const URL = 'https://pokeapi.co/api/v2/pokemon/';
URL у нас постоянен и может где-то понадобиться, поэтому можно вынести его за функцию. И лучше детализировать название, например `POKEMON_URL`
Часто в проектах делают файлик типа `contants/urls.js` и туда скидывают разные ссылки, что используются в проекте. Чтоб всё было в одном месте.

2023-07-08 15:56 UTC, Grinv commented on 10-pokemon-promise/main.js
> +    .then((data) => console.log(data))
Ну как так :/ та же самая проблема, что и в прошлом задании :/ Не надо сайт эффекты. `getPokemon` должна только возвращать данные и ничего больше. 

И далее уже делаешь с данными, что необходимо:
```javascript
getPokemon('bulbasaur').then(result => console.log(result))
```
либо если одно и тоже надо делать, делаешь одну функцию-обработчик и её передаёшь в then:
```javascript
const consolePokemon = (pokemonData) => console.log(pokemonData);
getPokemon('bulbasaur').then(consolePokemon)

2023-07-08 15:56 UTC, Grinv commented on 11-geolocation/main.js
> +btn.addEventListener('click', getCurrentCoords);
Тоже самое, что и в задании с покемонами. Функция getCurrentCoords только забирает данные и передаёт дальше, больше она ничего не должна делать.

2023-07-08 15:56 UTC, Grinv commented on 11-geolocation/main.js
> +        console.log(navigator.geolocation);
Ненужный console.log
Постарайся перед отправкой на код ревью проверять код на мусор, лишние console.log, лишний закомментированный код (иногда бывает не лишний, но это уже внутренние договорённости и частные случаи проекта 😁)

2023-07-08 15:56 UTC, Grinv commented on 12-promise-race/main.js
> +async function race(arr) {
race, внутри которого вызываем race? Нет, неправильно понял задание :)
Нам надо написать полифилл для race. Представить, что у нас не существует Promise.race и написать его собственную реализацию.

2023-07-08 15:56 UTC, Grinv commented on 12-promise-race/main.js
> +  const res = await fetch('https://jsonplaceholder.typicode.com/users/' + id);
Лучше ссылки выносить в константы и за функцию.

2023-07-08 18:07 UTC, MAChapurin commented on 10-pokemon-promise/main.js
> +    .then((data) => console.log(data))
Исправлено

2023-07-08 18:39 UTC, MAChapurin commented on 11-geolocation/main.js
> +btn.addEventListener('click', getCurrentCoords);
Разбил на две функции, одна отвечает за получение данных, другая за рендер

2023-07-08 18:40 UTC, MAChapurin commented on 11-geolocation/main.js
> +        console.log(navigator.geolocation);
Убрал

2023-07-08 20:55 UTC, MAChapurin commented on 12-promise-race/main.js
> +  const res = await fetch('https://jsonplaceholder.typicode.com/users/' + id);
ok

2023-07-08 20:55 UTC, MAChapurin commented on 12-promise-race/main.js
> +async function race(arr) {
Переделал

2023-07-10 10:03 UTC, Grinv requested changes

2023-07-10 10:03 UTC, Grinv commented on 10-pokemon-promise/main.js
> +getPokemonEffect('ditto', POKEMON_EFFECT_URL).then(log);
Тут нам не нужно передавать `effectUrl` :)
Работа впринципе очень похожа на предыдущую. В прошлой работе мы прокидывали в функцию 2 вещи
1) Какой покемон нам нужен
2) Что с этим покемоном делать

В этом задании всё тоже самое, только мы callback превратили в then
Не нужно прокидывать ссылку внутрь функции getPokemonEffect, у нас там только кастомизируется название покемона.
```javascript
const POKEMON_EFFECT_URL = 'https://pokeapi.co/api/v2/pokemon/';

function log(...args) {
   console.log(...args);
}

function getPokemonEffect(pokemonName) {
   return fetch(`${POKEMON_EFFECT_URL}${pokemonName}`)
      // ...
}

getPokemonEffect('bulbasaur').then(log);

2023-07-10 10:03 UTC, Grinv commented on 11-geolocation/main.js
> +  renderCoords(position);
В данном случае можно в callback просто передать функцию без вызова из функции другой функции.

```javascript
const btn = document.querySelector('button');
const position = document.querySelector('#pos');

btn.addEventListener('click', renderCoords);

function renderCoords() {
  getCurrentCoords()
    .then(({ latitude, longitude }) => {
      position.textContent = `${latitude} ${longitude}`;
    })
    .catch((error) => {
      position.textContent = error.message;
    });
}

2023-07-10 10:03 UTC, Grinv commented on 12-promise-race/main.js
> +Promise.prototype.constructor.myRace = function (promises) {
Советую не изменять прототипы системных встроенных объектов, так можно легко нарваться на проблемы, которые будет очень сложно в будущем поймать.

Лучше сделать простой метод
В будущем его можно будет вынести в папку utils и оттуда уже импортировать и использовать.

2023-07-10 10:03 UTC, Grinv commented on 12-promise-race/main.js
> +    promises.map((promise) => promise.then(resolve, reject));
Да, правильно👍
Очень круто, что в then второй аргумент прокинул, немногие про это знают. Сам прочитал и использовал или просто скопировал чужой код?))

2023-07-10 10:03 UTC, Grinv commented on 12-promise-race/main.js
> +raceUser([getUserById(1), getUserById(2), getUserById(13)]).then(console.log);
Я в данном случае не вижу смысла выносить логику в функции raceUser. Если б логика была какая-то сложная, то имело бы смысл. Но в данном случае там всё в одну строчку умещается :) Так что я бы вынес всё сюда.

```javascript 
myRace([getUserById(1), getUserById(2), getUserById(13)])
   .then(console.log)
   .catch(error => console.log(error))

2023-07-10 11:31 UTC, MAChapurin commented on 10-pokemon-promise/main.js
> +getPokemonEffect('ditto', POKEMON_EFFECT_URL).then(log);
Вынес.

2023-07-10 11:52 UTC, MAChapurin commented on 11-geolocation/main.js
> +  renderCoords(position);
Деструктуризация наше всё.

2023-07-10 12:01 UTC, MAChapurin commented on 12-promise-race/main.js
> +Promise.prototype.constructor.myRace = function (promises) {
Ну я читал как их писать везде начало [obj].prototype.method = function(...args){...}

2023-07-10 12:50 UTC, MAChapurin commented on 12-promise-race/main.js
> +raceUser([getUserById(1), getUserById(2), getUserById(13)]).then(console.log);
Немного поменял логику

2023-07-10 13:00 UTC, MAChapurin commented on 12-promise-race/main.js
> +    promises.map((promise) => promise.then(resolve, reject));
И читал и подсматривал, в данном случае если убрать reject, то ошибка будет вылетать при каждом вызове

2023-07-11 03:09 UTC, Grinv commented on 12-promise-race/main.js
> +Promise.prototype.constructor.myRace = function (promises) {
Да, кажется, что это очень логично. Но опять же, это надо быть супер уверенным в том, что делаешь.
Проверять на присутствие метода на текущем клиенте + она врятли будет в точности повторять поведение нативного метода. Где-то поведение точно будет отличаться. И потом это можно очень долго отлавливать.
Лучше явно указывать, что да, это моя собственная функция, написанная собственными руками.

2023-07-11 03:16 UTC, Grinv approved these changes

2023-07-11 03:16 UTC, Grinv commented on 10-pokemon-promise/main.js
> +    .catch((error) => console.log(error.message));
А если нам надо извне ошибку обработать?) Я бы её дальше прокидывал. Ну ладно, оставим на самостоятельную работу.

2023-07-11 03:16 UTC, Grinv commented on 11-geolocation/main.js
> +btn.addEventListener('click', renderCoords);
Да, так гораздо читабельнее и всё на своих местах👍

2023-07-11 03:17 UTC, merged