ready for five review
MAChapurin/javascript-advanced pull request #6
Opened 2023-07-11 03:40 UTC by MAChapurin

2023-07-13 17:28 UTC, Grinv requested changes

2023-07-13 17:28 UTC, Grinv commented on 13-buttons/main.js
> +}
Ну, тут задание совсем не про генераторы) И для данной фичи это оверкилл.
Но молодец, что применил.

2023-07-13 17:28 UTC, Grinv commented on 13-buttons/main.js
> +    countElement.textContent = addOne.next().value;
А давай попробуем у каждой кнопки сделать свой счётчик нажатий. Подумай, где мы можем их хранить.

2023-07-13 17:28 UTC, Grinv commented on 13-buttons/main.js
> +});
По поводу вёрстки - подумай, как сделать, чтоб кнопки не изменяли свою ширину при нажатии, некрасиво выглядит.

2023-07-13 17:33 UTC, MAChapurin commented on 13-buttons/main.js
> +}
Я относительно недавно про них узнал, и не удержался, так то можно обычной переменной это все обыграть

2023-07-13 17:34 UTC, MAChapurin commented on 13-buttons/main.js
> +    countElement.textContent = addOne.next().value;
Сейчас что нибудь придумаю

2023-07-13 17:34 UTC, MAChapurin commented on 13-buttons/main.js
> +});
ok

2023-07-14 16:33 UTC, Grinv commented on 13-buttons/main.js
> +}
Да, я так и понял) Как и сказал, похвально, что применил, но в данном случае это оверкилл)

2023-07-14 16:41 UTC, Grinv approved these changes

2023-07-14 16:41 UTC, Grinv commented on 13-buttons/main.js
> +});
Кнопки всеравно немного дёргаются, но так гораздо лучше)

2023-07-14 16:41 UTC, Grinv commented on 13-buttons/main.js
> +const btnsCount = document.querySelectorAll('.btn');
Почему `btnsCount`? Это ж просто `buttons`)

2023-07-14 16:41 UTC, merged